//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAjaxMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int ProductID { get; set; }
        public int ProductNO { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }
    }
}
