//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAjaxMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_Customers
    {
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public string CustomerName { get; set; }
        public int CustomerNO { get; set; }
        public int Quantity { get; set; }
        public int Total { get; set; }
        public System.DateTime Date { get; set; }

        [NotMapped]
        public String strDate { get; set; }

    }
}
