//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAjaxMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sales
    {
        public int SalesID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public int Quantity { get; set; }
        public int Total { get; set; }
        public System.DateTime Date { get; set; }
    }
}
